site_name: Data Catering
site_url: https://data.catering/
repo_url: https://github.com/data-catering/data-caterer
repo_name: data-caterer

extra_css:
  - stylesheets/extra.css

plugins:
  - open-in-new-tab
  - search
  - optimize
  - social
  - privacy

theme:
  name: material
  logo: diagrams/logo/data_catering_transparent.svg
  favicon: diagrams/logo/data_catering_transparent.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.path
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - toc.integrate
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: amber
      accent: lime
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Home: 'index.md'
  - Get Started: 'get-started/docker.md'
  - Setup:
      - 'setup/index.md'
      - Design: 'setup/design.md'
      - Guide:
          - 'setup/guide/index.md'
          - Scenario:
              - First Data Generation: 'setup/guide/scenario/first-data-generation.md'
              - Multiple Records Per Column Value: 'setup/guide/scenario/records-per-column.md'
              - Foreign Keys Across Data Sources: 'setup/guide/scenario/batch-and-event.md'
              - Data Validations: 'setup/guide/scenario/data-validation.md'
              - Auto Generate From Data Connection: 'setup/guide/scenario/auto-generate-connection.md'
              - Delete Generated Data: 'setup/guide/scenario/delete-generated-data.md'
              - Generate Batch and Event Data: 'setup/guide/scenario/batch-and-event.md'
          - Data Sources:
              - Files (CSV, JSON, ORC, Parquet): 'setup/guide/scenario/first-data-generation.md'
              - Cassandra: 'setup/guide/data-source/cassandra.md'
              - Kafka: 'setup/guide/data-source/kafka.md'
              - Solace: 'setup/guide/data-source/solace.md'
              - Marquez Metadata Source: 'setup/guide/data-source/marquez-metadata-source.md'
              - OpenMetadata Source: 'setup/guide/data-source/open-metadata-source.md'
              - HTTP: 'setup/guide/data-source/http.md'
      - Configuration: 'setup/configuration.md'
      - Connection: 'setup/connection.md'
      - Generator:
          - Data Generator: 'setup/generator/data-generator.md'
          - Record Count: 'setup/generator/count.md'
      - Validation:
          - 'setup/validation.md'
          - Basic: 'setup/validation/basic-validation.md'
          - Group by/Aggregate: 'setup/validation/group-by-validation.md'
          - Upstream: 'setup/validation/upstream-data-source-validation.md'
          - Column Names: 'setup/validation/column-name-validation.md'
          - External Source: 'setup/validation/external-source-validation.md'
      - Report:
          - HTML Report: 'setup/report/html-report.md'
          - Alert: 'setup/report/alert.md'
      - Foreign Keys: 'setup/foreign-key.md'
      - Delete Data: 'setup/delete-data.md'
      - Deployment: 'setup/deployment.md'
      - Advanced: 'setup/advanced.md'
  - Use Case:
      - 'use-case.md'
      - Business Value: 'use-case/business-value.md'
      - Comparison: 'use-case/comparison.md'
      - Roadmap: 'use-case/roadmap.md'
      - Blog:
          - Shift Left Data Quality: 'use-case/blog/shift-left-data-quality.md'
  - About:
      - 'about.md'
      - Pricing: 'sponsor.md'
      - Terms of service: 'legal/terms-of-service.md'
      - Privacy policy: 'legal/privacy-policy.md'
  - Demo: 'demo.md'


extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/data-catering/shared_invite/zt-2664ylbpi-w3n7lWAO~PHeOG9Ujpm~~w
    - icon: fontawesome/brands/github
      link: https://github.com/data-catering/data-caterer-example
    - icon: fontawesome/brands/medium
      link: https://medium.com/@pflooky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/peter-flook/
    - icon: fontawesome/solid/paper-plane
      link: mailto:peter.flook@data.catering
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCNJACecY00X3JuV99UOySqQ
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/datacatering
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/datacatering
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-4098CTH5TX

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
