name: Run performance benchmark tests

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data-caterer-example repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Checkout datafusion-comet repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          repository: apache/datafusion-comet
          path: benchmark/build/datafusion-comet
      - name: Get Spark query engine jars
        run: bash benchmark/setup_query_engine_jars.sh
      - name: Run benchmark script
        run: bash benchmark/run_benchmark.sh
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Add benchmark results